server:
  port: 8087

spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: 4278
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        jdbc.lob.non_contextual_creation: true


